let str1 = "+--------+--------+\n";
let text = "";
text += str1;
text += "| Vardas | Amzius |\n";
text += str1;
text += "| Tomas  | 24     |\n";
text += "| Jonas  | 26     |\n";
text += "| Juste  | 25     |\n";
text += str1;
console.log(text);
document.getElementById("text").innerHTML="JS testas";