let number1 = 4;
let number2 = 5;
console.log(`${number1} - ${number2} = ${number1 - number2}`);
console.log(`${number1} + ${number2} = ${number1 + number2}`);
console.log(`${number1} * ${number2} = ${number1 * number2}`);
console.log(`${number1} / ${number2} = ${number1 / number2}`);
console.log("================================================");
console.log(`${-1 + 4 * 6}`);
console.log(`${(35 + 5) % 7}`);
console.log(`${14 + (-4 * 6) / 12}`);
console.log(`${2 + (15 / 6) * 1 - (7 % 2)}`);
